In [ ]:
# Opencv를 파이썬 언어로 프로그래밍한다 = Numpy배열을 다루는 것
# 그러므로, Numpy를 모른다는 건? Opencv를 파이썬 언어로 사용하는 게 불가능하다는 뜻이다.

In [1]:
# 차원변경

In [2]:
# 브로드캐스팅 연산

In [4]:
mylist = list(range(10))

In [5]:
mylist

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
len(mylist)

10

In [9]:
for i in range(len(mylist)): #len(): 함수의 길이
    mylist[i] = mylist[i] + 1

In [10]:
mylist

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [11]:
# 브로드캐스팅 연산
# numpy 배열에 +1(더하기1) 연산을 해도 같은 결과가 나온다
# 모든 산술 연산이 가능합니다.

In [13]:
import numpy as np

In [14]:
a = np.arange(10)

In [15]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
b = np.arange(6)

In [20]:
b

array([0, 1, 2, 3, 4, 5])

In [21]:
b.reshape(2, -1)

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
b1 = b.reshape(2, -1) # -1의 의미가 뭘까?

In [24]:
b1 * 2

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [25]:
# 인덱싱과 슬라이싱
# numpy 배열은 파이썬 리스트처럼 인덱스로 접근할 수 있다.

In [40]:
r = np.arange(12)

In [41]:
r1 = r.reshape(3,4)

In [42]:
r1[1]

array([4, 5, 6, 7])

In [43]:
r1[1,2]

6

In [44]:
# 팬시 인덱싱
# 배열 인덱스에 다른 배열을 전달해서 원하는 요소를 선택하는 방법

In [45]:
a = np.arange(5)

In [46]:
a

array([0, 1, 2, 3, 4])

In [47]:
a[[1,3]]

array([1, 3])

### 병합과 분리
#### 1. 배열(array)들을 이어 붙여서 크기를 키우는 방법
#### 2. 새로운 차원을 만들어 서로서로 끼워넣는 방법
#### numpy.hstack(arrays): arrays 배열을 수평으로 병합
#### numpy.vstack(arrays): arrays 배열을 수직으로 병합
#### numpy.concateante(arrays, axis = 0): array 배열을 지정한 축 기준으로 병합
#### numpy.stack(arrays, axis=0): arrays 배열을 새로운 축으로 병합
##### arrays: 병합 대상 배열(튜플), axis:작업할 대상 축 번호

In [49]:
a = np.arange(4).reshape(2,2)

In [50]:
a

array([[0, 1],
       [2, 3]])

In [51]:
b = np.arange(10, 14).reshape(2,2)

In [52]:
b

array([[10, 11],
       [12, 13]])

In [53]:
np.vstack( (a,b) ) #수직병합

array([[ 0,  1],
       [ 2,  3],
       [10, 11],
       [12, 13]])

In [54]:
np.hstack( (a,b) ) #수평병합

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13]])

In [55]:
np.concatenate((a,b), 0)

array([[ 0,  1],
       [ 2,  3],
       [10, 11],
       [12, 13]])

In [56]:
np.concatenate((a,b), 1)

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13]])

In [57]:
np.concatenate((a,b), 2) #배열의 차원에 따라 axis의 범위도 정해져 있다.

AxisError: axis 2 is out of bounds for array of dimension 2

In [64]:
a3 = np.arange(13,25).reshape(2,2,3)

In [65]:
a3

array([[[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [60]:
b3 = np.arange(12).reshape(3,2,2)

In [61]:
b3

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [66]:
np.concatenate((a3,b3), 2) #이건 뭔 소리냐

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [67]:
a = np.arange(12).reshape(4,3)
b = np.arange(10,130,10).reshape(4,3)

In [68]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [69]:
b

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [ ]:
# 차원(축)이 새로 늘어나는 방법
# 축 번호를 지정하지 않으면 0번을 의미하고, -1은 마지막 축 번호를 의미한다.

In [71]:
c = np.stack((a,b),0)

In [72]:
c

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90],
        [100, 110, 120]]])

In [74]:
test = np.array([[0,1,2],
              [3,4,5],
              [6,7,8],
              [9,10,11]])

In [75]:
test.shape

(4, 3)

In [76]:
#검색
#Numpy배열을 사용하여 관심 있는 데이터만을 찾거나 바꾸는 작업을 수행할 수 있다

In [77]:
a = np.arange(10, 20)

In [78]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [80]:
np.where(a > 15) # a>15보다 큰 값을 갖는 인덱스를 구한다.

(array([6, 7, 8, 9], dtype=int64),)

In [81]:
np.where(a>15, 1, 0) #15보다 큰 값은 1로 채우고, 그렇지 않은 값은 0으로 채운다

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1])

In [82]:
b = np.arange(12).reshape(3,4)

In [83]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
coords = np.where(b>6) #

In [85]:
coords

(array([1, 2, 2, 2, 2], dtype=int64), array([3, 0, 1, 2, 3], dtype=int64))

In [86]:
np.stack((coords[0], coords[1]), -1) #

array([[1, 3],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3]], dtype=int64)

In [87]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [88]:
np.nonzero(a>15)

(array([6, 7, 8, 9], dtype=int64),)

In [89]:
np.where(a>15)

(array([6, 7, 8, 9], dtype=int64),)

In [90]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
np.nonzero(b>6)

(array([1, 2, 2, 2, 2], dtype=int64), array([3, 0, 1, 2, 3], dtype=int64))

In [92]:
np.where(b>6)

(array([1, 2, 2, 2, 2], dtype=int64), array([3, 0, 1, 2, 3], dtype=int64))

In [ ]:
#numpy를 이용한 이미지 생성

In [2]:
import cv2
import numpy as np

In [3]:
img = np.zeros((120,120), dtype=np.uint8) 
#120*120 2차원 배열 생성, 검은색 흑백이미지
#Opencv이미지를 표현하기 위한 Numpy 배열은 반드시 dtype이 uint8이어야 합니다.

In [ ]:
# 0 ~ 255, 0: 검은색 255: 흰색

In [95]:
img[25:35, :] = 45
img[55:65, :] = 115
img[85:95, :] = 160
img[:, 35:45] = 205
img[:, 75:85] = 255

In [ ]:
cv2.imshow('Gray', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np

img = np.zeros((120,120, 3), dtype=np.uint8)    # 120x120 2차원 배열 생성, 3채널 컬러 이미지
img[25:35, :] = [255,0,0]                       # 25~35행 모든 열에 [255,0,0], 파랑색 할당 
img[55:65, :] = [0, 255, 0]                     # 55~65행 모든 열에 [0,255,0], 초록색 할당 
img[85:95, :] = [0,0,255]                       # 85~95행 모든 열에 [0,0,255], 빨강색 할당 
img[:, 35:45] = [255,255,0]                     # 모든행 35~45 열에 [255,255,0], 하늘색 할당 
img[:, 75:85] = [255,0,255]                     # 모든행 75~85 열에 [255,0,255], 분홍색 할당 
cv2.imshow('BGR', img)
if cv2.waitKey(0) & 0xFF == 27:
    cv2.destroyAllWindows()